fruits=["apple","oranges","banana"]
fruits.append("cherry")
print(fruits)
fruits.remove("cherry")
print(fruits)
fruits.pop(1)
my_fruits=fruits.pop(1)
print(fruits)
print(my_fruits)
fruits_2=["cheery","tomato"]
fruits_3=fruits+fruits_2
print(fruits_3)
fruits.extend(fruits_2)
print(fruits)
fruits_2.clear()
fruits_4=("apple","orange","something")
print(fruits_4)
print(fruits_4[1])
new_list=list(fruits_4)
new_list.append("tomato")
fruits_4=tuple(new_list)
fruits_5={"apple","oranges","oranges","oranges"}
print(fruits_5)

